### PR TITLE
Report from Maps page

### PR DESCRIPTION
**Pull request by MMcCormick**
Notes:

-should dump.rdb be ignored with .gitignore?
-doesn't auto-refresh after submission

### CODE REVIEW

**Comment by jayvan** [comment]
I really like the in-line voting, but we're going to have to look at optimizing this first.
The size of the main page went from 50kb to 500kb
The time to DOM ready went from 300ms to 2650ms
Because the DOM is so heavy, it also takes 4367ms for the in-line form to appear.

I think there are big saving to having 1 report form, and moving it, rather than having 1 form per map.

**Comment by MMcCormick** [comment]
Yeah, you're right. But it shouldn't be hard to just copy one form and then
fill in the map field value.

**Comment by MMcCormick** [comment]
Much faster for me, now. Let me know if you have any other improvements.

**Comment by MMcCormick** [comment]
Oh, one other thing - I commented out the conditional hiding / showing of the thumb buttons, so that the form could be accessed via the downvote. Obviously this isn't right for user experience, but I wanted your input on how you want it to work. @jayvan

**Comment by jayvan** [comment]
Maybe show a + icon instead? The materialize website has a list of icons
available. I can take a look and probably merge this tonight when I get
home.

**Comment by MMcCormick** [comment]
Oddly enough, Materialize didn't have one, but I styled a + that looks natural, I think.

**Pull request merged**
